# Generated by Django 5.1.5 on 2025-02-20 09:37

import entry_exit_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, default='media/students/default.jpg', null=True, upload_to=entry_exit_app.models.getFilename),
        ),
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='media/barcodes/'),
        ),
    ]
