# Generated by Django 5.1.5 on 2025-02-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit_app', '0002_student_profile_image_alter_student_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='barcode',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='barcodes/'),
        ),
    ]
