# Generated by Django 5.1.5 on 2025-02-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry_exit_app', '0003_alter_student_barcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['rollno']},
        ),
    ]
